"""Shared constants to reduce hardcoded strings across modules."""

ROLE_SUPERADMIN = "superadmin"
ROLE_ADMIN = "admin"
ROLE_USER = "user"
ROLE_SELLER = "seller"

FLASH_SUCCESS = "success"
FLASH_WARNING = "warning"
FLASH_DANGER = "danger"
FLASH_INFO = "info"

SALE_STATUS_CONFIRMED = "confirmada"
SALE_STATUS_CANCELLED = "anulada"
PAYMENT_STATUS_PENDING = "pendiente"
PAYMENT_STATUS_APPROVED = "approved"

SUPPORT_TICKET_STATUS_PENDING = "pendiente"
PASSWORD_RECOVERY_STATUS_PENDING = "pendiente"
PASSWORD_RECOVERY_STATUS_ATTENDED = "atendida"
PASSWORD_RECOVERY_STATUS_CLOSED = "cerrada"

SESSION_REFERRAL_CODE = "referral_code"
SESSION_REFERRAL_COOKIE = "stockarmobile_ref"
SESSION_PASSWORD_RECOVERY_TEMP_PASSWORD = "password_recovery_temp_password"
SESSION_PASSWORD_RECOVERY_TEMP_PASSWORD_USER = "password_recovery_temp_password_user"
SESSION_POST_REGISTER_ONBOARDING_COMPANY_ID = "post_register_onboarding_company_id"

HEADER_RETRY_AFTER = "Retry-After"
HEADER_CSRF_TOKEN = "X-CSRFToken"
HEADER_REQUEST_ID = "X-Request-ID"
HEADER_CORRELATION_ID = "X-Correlation-ID"

CONFIG_IS_PRODUCTION_ENV = "IS_PRODUCTION_ENV"
CONFIG_IS_PYTEST_CONTEXT = "IS_PYTEST_CONTEXT"
CONFIG_COMPANY_PIN_SESSION_TTL_MINUTES = "COMPANY_PIN_SESSION_TTL_MINUTES"
