"""Notifications for customer orders generated by the AI seller."""

from __future__ import annotations

from datetime import timedelta


def build_ai_order_notifications():
    """Build tenant notifications for recent WhatsApp AI seller orders."""
    from flask import url_for
    from flask_login import current_user

    if not getattr(current_user, "is_authenticated", False):
        return []
    if getattr(current_user, "role", None) not in {"admin", "user"}:
        return []

    from app import Payment, Quote, get_current_company_id, utcnow

    company_id = get_current_company_id()
    if not company_id:
        return []

    cutoff = utcnow() - timedelta(days=7)
    marker = "Pedido generado por el Vendedor 24 hs de StockARmobile."
    quotes = (
        Quote.query.filter(
            Quote.company_id == int(company_id),
            Quote.observations == marker,
            Quote.date >= cutoff,
        )
        .order_by(Quote.date.desc(), Quote.id.desc())
        .limit(8)
        .all()
    )
    payments = (
        Payment.query.filter(
            Payment.company_id == int(company_id),
            Payment.provider == "mercadopago_ai_order",
            Payment.created_at >= cutoff,
        )
        .order_by(Payment.id.desc())
        .limit(50)
        .all()
    )

    by_quote = {}
    prefix = f"flow:ai_order|company_id:{int(company_id)}|quote_id:"
    for payment in payments:
        reference = str(payment.external_reference or "")
        if not reference.startswith(prefix):
            continue
        quote_part = reference[len(prefix):].split("|", 1)[0]
        if quote_part.isdigit() and int(quote_part) not in by_quote:
            by_quote[int(quote_part)] = payment

    items = []
    for quote in quotes:
        payment = by_quote.get(quote.id)
        customer = (
            getattr(getattr(quote, "client", None), "name", None)
            or getattr(quote, "consumer_name", None)
            or "Consumidor final"
        )
        number = getattr(quote, "number", None) or f"P-{quote.id:06d}"
        currency = getattr(quote, "currency", None) or "ARS"
        total = float(getattr(quote, "total_amount", 0) or 0)
        href = url_for("whatsapp_agent.ai_order_detail", quote_id=quote.id)

        if getattr(quote, "converted_sale_id", None):
            items.append(
                {
                    "type": "success",
                    "title": "Pedido IA confirmado",
                    "body": f"{number} de {customer} · {currency} {total:.2f}. Pago aprobado y venta confirmada.",
                    "href": href,
                }
            )
            continue

        payment_status = str(getattr(payment, "status", "pending") or "pending").lower() if payment else "pending"
        if payment_status == "approved":
            items.append(
                {
                    "type": "warning",
                    "title": "Pago aprobado · revisar pedido IA",
                    "body": f"{number} de {customer} tiene el pago aprobado, pero todavía no figura como venta confirmada.",
                    "href": href,
                }
            )
        elif payment_status in {"pending", "in_process", "authorized"}:
            items.append(
                {
                    "type": "primary",
                    "title": "Nuevo pedido IA",
                    "body": f"{number} de {customer} · {currency} {total:.2f}. Esperando aprobación de pago.",
                    "href": href,
                }
            )
        else:
            items.append(
                {
                    "type": "danger",
                    "title": "Incidencia en pedido IA",
                    "body": f"{number} de {customer} · estado de pago: {payment_status.replace('_', ' ')}.",
                    "href": href,
                }
            )
    return items[:6]
